### ISSUE TITLE
As an instructor, I want to post reminders that are visible to that participants so that they are aware even if they miss oral or other reminders

### ISSUE THREAD

**Issue by mlinderm** [csci312-common-v2/class-interactor#19]

**Comment by KatieMacalintal** [comment]
# Ideas: 
### Potential Behavior  
- Use [Alerts](https://mui.com/material-ui/react-alert/); Unsure if you can have multiple actions 
- Students cannot close reminders on a local view 
- Reminders live on the page until the admin deletes it 
- Deleting a reminder removes it from the database 

### Updated Student View 
![Image](https://github.com/csci312-common-v2/class-interactor/assets/125110058/1e0f64f2-41f4-422b-9e71-8c9c4c35743c)

### Updated Console (Instructor) View 
![Image](https://github.com/csci312-common-v2/class-interactor/assets/125110058/05f51f76-75c3-4094-87e0-007097e35c7a)

### Updated CRC Cards
Room |  
-- | --
Knows name |  
Knows members | User via Roster
Knows polls | Poll
**Knows reminders** | **Reminder**

Reminder |  
-- | --
Knows title |  
Knows description | 
Knows room | Room
